### ISSUE TITLE
cdn.podigee.com/ppp/podigee-podcast-player.js returns 403

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#1]

**Comment by benzimmer** [comment]
As far as I can see that path never worked (or at least never should have). Please use https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js from now on. This will also work in the future.

**Comment by funkenstrahlen** [comment]
Ok great. I got that url from the Readme, so you might want to update that.

**Comment by funkenstrahlen** [comment]
Thanks a lot!
