### ISSUE TITLE
integrate podlove subscribe button?

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#10]
Have you considered adding the podlove subscribe button to the player, so a listeners can subscribe directly if he likes the podcast?

**Comment by benzimmer** [comment]
Yes, this is definitely on the roadmap but not that easy because the button is based on being an iframe itself. Still looking for a solid plan here :)

**Comment by benzimmer** [comment]
This has been implemented a while ago. Forgot to close this 🤷‍♂️
