### ISSUE TITLE
ruby script to generate config.json for each episode required for embedding

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#12]
Do you thing this idea is worth the time? https://github.com/funkenstrahlen/rss-to-podigee-json

Note: implementation not finished at all!

**Comment by benzimmer** [comment]
Nice :)

I was thinking about providing a little web application where you can either input your feed and choose an episode to use in the player or enter data for a single audio file manually and get an embed link. The JSON configuration would then be hosted with the web application. Idea would be that the application itself would be open-source. Podigee hosts an instance of it which can be used for free by non-commercial projects ("commercial" meaning actually business-related, not just having a flattr button on the page:) ). Something like your library would be kind of the core for the project :)

**Comment by funkenstrahlen** [comment]
I currently use podlove and would love to use the podigee player on my site. However for the embedding to work I need the config files for each episode. That's why I came up with this script to generate the files.

It might be a better idea if the podlove plugin manages those files thought. Have you talked to the podlove project? What are their thoughts about integrating the podigee player?

> I was thinking about providing a little web application where you can either input your feed and choose an episode to use in the player or enter data for a single audio file manually and get an embed link.

Currently this might be very useful. I hope more podcast websites will provide an embeddable player themselves in the future, so this service might not be required any more. It might be better to spend more time on fixing the problem on the source instead of the symptoms.

**Comment by benzimmer** [comment]
I already talked to @eteubert about integration into the publisher, but I currently don't know how far he got. Perhaps he can answer himself :)

About the web app: I think in the first place this would be a kind of show-case for the player, but probably useful for some people in the meantime. And the effort is pretty minimal as far as I see.

**Comment by eteubert** [comment]
The Podigee player will definitely be an option in the Publisher in the near future. I have it working in single episodes, if I remember correctly, but some issues when multiple players are on a single plage.

I expect the player to be in the Publisher by release 2.4.0.

**Comment by funkenstrahlen** [comment]
@eteubert That's nice! I really appreciate that. However have you seen how the player can be made embeddable? It requires a `config.json` file for each episode, which can then be linked to in the embed code. So either the podcast creator has to create these config files manually or the podlove plugin has to create them.

What's your opinion on that? Can podlove somehow create those files?

**Comment by benzimmer** [comment]
@eteubert The issue with multiple players should be resolved for now. For reference have a look at #11

**Comment by benzimmer** [comment]
@funkenstrahlen Quick demo of what I meant above: https://podigee-quickplay.herokuapp.com/

You can generate a configuration by providing feed URL and episode guid like this:

`/player_config?feed_url=http://example.com/feed/mp3&episode_guid=guid-example`

**Comment by funkenstrahlen** [comment]
That's actually a pretty cool service! I saw the data configuration is set as an url to this service:

* Does this fetch the feed on each access to the player? Or does it cache the json file?
* All players will stop working as soon as the service is down right? But that's true for the player's source code too.

I like the way I am able to select an episode directly from the feed.

Long term I would like to see embeddable players on podcaster websites though. This way they can host the data json themselves.

**Comment by benzimmer** [comment]
Did some improvements and moved to a permanent domain https://quickplay.podigee.com

- Player configurations themselves are cached, the first load of the feed not yet, but as the mechanism is already there it's a minor thing
- Players will stop working if the service goes down, but as this little app as well as the player itself are open source nobody has to take that risk

I see this more as a playground or reference implementation (I think something like this does not exist currently), but we'll see how it's perceived.

The repository for the service can be found here: https://github.com/podigee/podigee-quickplay

I also added buttons for heroku and cloud.docker.com for dead easy deployment if you want to run it yourself. The readme still needs a little :heart: though :)

**Comment by funkenstrahlen** [comment]
This is actually really cool and useful! Thanks a lot for building that service!

**Comment by benzimmer** [comment]
Glad you like it! I'll close this issue then :)
