### ISSUE TITLE
Configuration example from README does not work

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#14]
I just tried to embed the player with the example provided in the readme using a local configuration. I added this `playerConfiguration` to the end of my page:

```html
	<script>
		window.playerConfiguration = {
		  "options": {
		    "theme": "default",
		    "sslProxy": "https://example.com/ssl-proxy/",
		    "startPanel": "Playlist"
		  },
		  "extensions": {
		    "EpisodeInfo": {},
		    "Playlist": {
		      "disabled": true
		    }
		  },
		  "podcast": {
		    "feed": "https://cdn.podigee.com/ppp/samples/feed.xml",
		  },
		  "episode": {
		    "media": {
		      "mp3": "https://cdn.podigee.com/ppp/samples/media.mp3"
		    },
		    "coverUrl": "https://cdn.podigee.com/ppp/samples/cover.jpg",
		    "title": "FG009 Wirtschaftspolitischer Journalismus",
		    "subtitle": "Wie Henrik Müller in Dortmund wirtschaftspolitischen Journalismus lehrt und erforscht. Und was guten Wirtschaftsjournalismus ausmacht.",
		    "url": "http://forschergeist.de/podcast/fg009-wirtschaftspolitischer-journalismus/",
		    "embedCode": "<script class=\"podigee-podcast-player\" src=\"https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js\" data-configuration=\"https://podigee.github.io/podigee-podcast-player/example/config.json\"><\/script>",
		    "description": "Raus aus der prallen journalistischen Praxis, rein in die Gremien-Universität. Henrik Müller hat diesen ungewöhnlichen Schritt gewagt: 2013 übernahm der damalige stellvertretende Chefredakteur des "manager magazin" den Lehrstuhl für wirtschaftspolitischen Journalismus am Institut für Journalistik der Technischen Universität Dortmund. Dort baut er seitdem die neuen Bachelor- und Master-Studiengänge für wirtschaftspolitischen Journalismus auf. Wie er diesen Wechsel zwischen den  Welten erlebt hat, was er seinen Studierenden vermitteln will und woran er forscht, erzählt der immer noch sehr umtriebige Autor ("Wirtschaftsirrtümer: 50 Denkfehler, die uns Kopf und Kragen kosten") und Spiegel-Online-Kolumnist in dieser anregenden Episode. Dabei geht es darum, was Wirtschaftsjournalismus leisten soll und muss, was Studierende erst mühsam über Lobbyismus lernen müssen und was eigentlich "gute Geschichten" sind."
		  }
		}
	</script>
```

This is how I embed the player:

```html
<script class="podigee-podcast-player" src="https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js" data-configuration="playerConfiguration"></script>
``` 

I see this error in my log:

```
GET https://cdn.podigee.com/podcast-player/playerConfiguration 403 ()
```

Looks like the player does not even consider the local option any more?

**Comment by benzimmer** [comment]
Directly above the error in your log you should also see something like:

```
fiddle.jshell.net/:79 Uncaught SyntaxError: Unexpected identifier
```

This is coming from an error in the example JSON :/. I fixed it in the last commit on develop. Please note that the player still won't render when using the example configuration because most of the assets can't be loaded. I'll leave this issue open as a reminder to update the example with valid data.

**Comment by funkenstrahlen** [comment]
I applied your changes to my code. Your are right, the JSON contained errors. However I think this does not address the issue I see.

The player tries to fetch the configuration from `https://cdn.podigee.com/podcast-player/playerConfiguration` despite the fact I defined it to use `data-configuration="playerConfiguration"`. So this should not prepend `https://cdn.podigee.com/podcast-player/`.

**Comment by benzimmer** [comment]
Everything works fine when the local configuration is valid. See here https://jsfiddle.net/46fvpbsj/

The reason why the player tries to fetch `https://cdn.podigee.com/podcast-player/playerConfiguration` is that it checks if the configuration passed in is a Javascript Object with certain attributes. If this is not the case it checks if the value is a String, assumes that it's a URL and tries to fetch the configuration from there.

I'll have a closer look why the example config does not work and try to improve the loading mechanism so it provides better error handling and most importantly error messaging for the user.

**Comment by funkenstrahlen** [comment]
Ok now I understand why the player tries to fetch the external URL. I will move to the external configuration in the future anyway to support embedding.
