### ISSUE TITLE
Theming documentation

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#15]
The readme says I can customize the look of the player. Where can I find any documentation on how to do that?

**Comment by funkenstrahlen** [comment]
By the way: I like the player style at the 4000hertz website. Is there any way you can make this theme public?

**Comment by benzimmer** [comment]
Sorry for the delay. I will add some documentation on how to write and integrate a custom theme in the next days.

About the 4000hertz theme: I'll see if they are up to making it an official theme. But even if not, once the documentation is out you'll see it's actually pretty easy to do something like this yourself :)

**Comment by benzimmer** [comment]
There is now some documentation available here https://github.com/podigee/podigee-podcast-player/blob/develop/docs/theming.md

If you need more, please let me know!

**Comment by funkenstrahlen** [comment]
This is really cool! Thank you!
