### ISSUE TITLE
Set initial progress & listen to playback events

### ISSUE THREAD

**Issue by bottiger** [podigee/podigee-podcast-player#16]
Is it possible to set an initial offset/progress for an episode. This would be very useful for resuming playback when it is known that the user has already listened to the first 15 minutes, or you manually want to start an episode at a specific point.

Secondly. Is it possible to hook up a callback function to various events like play/pause/finished etc.

**Comment by benzimmer** [comment]
What you already can do is to add a timestamp to the address the player resides on. For example https://podigee.github.io/podigee-podcast-player/#t=2800. The number is the time in seconds. You can create the URL by going to the share tab and using the "Start at" checkbox:

![screen shot 2016-08-24 at 09 04 00](https://cloud.githubusercontent.com/assets/164417/17921375/caea3710-69d9-11e6-9277-762c19d48558.png)

Currently there is no way to attach callbacks when you use standard variant of the player. If you instantiate it yourself (as done in https://github.com/podigee/podigee-podcast-player/blob/develop/src/html/podigee-podcast-player.html) you can simply attach to the `<audio>` tag's [MediaElementAPI](https://developer.mozilla.org/en/docs/Web/API/HTMLMediaElement). However, I will think about a way to expose those for the other use cases too somehow.

What exactly are you trying to achieve if I may ask?

**Comment by benzimmer** [comment]
I just remembered that I already did some research on the callback topic :)

Most likely we will implement the spec described here, but I can't give you a fixed date, because we're currently working on other things: https://github.com/embedly/player.js/blob/master/SPEC.rst

**Comment by bottiger** [comment]
@benzimmer Thank you very much. I actually just (like, 10 minutes ago) realized I can set the starting position as you described by digging through the source.

My use case is this: I'm the developer of an Android Podcast client - called [SoundWaves](https://play.google.com/store/apps/details?id=org.bottiger.podcast&hl=en). I want to create a simple web player where you can listen to episodes on your desktop computer.

The reason I wanted to hook into player events is so I can send the current state back to the app. I don't know a lot about javascript, so the MediaElementAPI may be enough for what I need.

**Comment by benzimmer** [comment]
Nice :) Let me know if I can support you in any way!

Btw.: Did you already stumble over http://podlove.org/podlove-subscribe-button/? I'm the maintainer and we're always happy to add new clients to the list.

**Comment by bottiger** [comment]
@benzimmer I have unfortunately never heard of podlove-subscribe-button before. However, you are welcome to add my app. However, I have just added the required URI schemes, and the should be live in a week or so.

You can support me in all the usual ways. Use the app and spread the word :) It's by no means a bug free experience, but it's (finally) getting there. I'm always interested in bug reports from users, since it can be hard to know where to focus.

Thanks

**Comment by benzimmer** [comment]
Hi! The version in the develop branch of this repository now supports the player.js spec: https://github.com/embedly/player.js/blob/master/SPEC.rst

Let me know if that works for you. I'll keep this issue open until this is merged in master.

**Comment by benzimmer** [comment]
Merged to master (commit d5776678b189f4e96ec1fa63838506bab8b93200)

**Comment by bottiger** [comment]
@benzimmer Thanks a lot.
