### ISSUE TITLE
Just feedback

### ISSUE THREAD

**Issue by haslinger** [podigee/podigee-podcast-player#17]
Hi guys, 

I am the guy who talked to Ben in Munich about using your player in Panoptikum: https://alpha.panoptikum.io/

I now embedded it, short feedback: Just works and awesome documentation.

Keep up the good work!

**Comment by benzimmer** [comment]
Sorry I did not answer this earlier! Thanks a lot for the kind works. Nice to see the player adopted in more and more projects 😃
