### ISSUE TITLE
Layout Problems with Transcript Search on Mobile Browsers

### ISSUE THREAD

**Issue by gholzmann** [podigee/podigee-podcast-player#19]
On iOS Safari and Android.

First the search bar looks correct:
![datei 24 11 16 10 36 23](https://cloud.githubusercontent.com/assets/1970014/20593286/0e3b61ec-b232-11e6-9447-7a09e6a891cf.png)

If you enter a search term, the search bar jumps down one line and the layout is messed up:
![datei 24 11 16 10 35 49](https://cloud.githubusercontent.com/assets/1970014/20593281/0b018ace-b232-11e6-94e2-c56c1db349cf.png)

The same on android:
![screenshot_20161124-103343](https://cloud.githubusercontent.com/assets/1970014/20593379/72540850-b232-11e6-8588-c5558bc6bf0d.png)

Example page to reproduce the problem:
https://auphonic.com/media/share/tr/podigee-player-test.html

**Comment by gholzmann** [comment]
The iOS Layout still has issues:
1. not the whole first line is visible (highlighted, with search result)
2. the interface elements in the search bar are off (especially the "x" button)

See this screenshot:

![datei 25 11 16 09 22 32](https://cloud.githubusercontent.com/assets/1970014/20618735/0b73a432-b2f1-11e6-9a2d-620525d0f1a4.png)

**Comment by gholzmann** [comment]
Btw.: on Android the "x" in the search bar is also a bit off, but not that much:

![screenshot_20161125-092558](https://cloud.githubusercontent.com/assets/1970014/20618780/47dc3f92-b2f1-11e6-9b28-545f14383ad4.png)

**Comment by benzimmer** [comment]
Should be fixed in Safari too now!
