### ISSUE TITLE
Disable Playlist extension

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#2]
I want to use the player to play just one single audio file. How can I disable the playlist extension?

**Comment by benzimmer** [comment]
You can now configure extensions to be disabled. For the playlist extension you now have two options:

1. Don't provide the feed in the `podcast` configuration branch.
2. Disable the extension entirely by adding something like this to the configuration:

```
...
"extensions": {
  "Playlist": {
    "disabled": true
  }
}
...
```

The change is already deployed to the CDN. If something is not working please let me know!

**Comment by funkenstrahlen** [comment]
Works perfectly! Thanks a lot for helping me out so fast!

**Comment by benzimmer** [comment]
Consider it an early christmas present ;)
