### ISSUE TITLE
Player does not show play button on mobile browsers

### ISSUE THREAD

**Issue by gholzmann** [podigee/podigee-podcast-player#21]
On mobile browsers (tested in iOS Safari and Android), the big play button always shows the loading animation instead of the play icon (see screenshot below).
However, if one clicks on the play button (which still shows the animation), the playback starts as it should. Afterwards it's possible to see the play/pause button.

On desktop browsers everything works as it should.

Tested with the following example:
https://auphonic.com/media/share/tr/podigee-cors.html
Player Configuration:
`window.playerConfiguration = {
        "options": {
          "theme": "default"
        },
        "episode": {
          "media": {
            "mp3": "https://traffic.libsyn.com/dancarlin/cswdcd09.mp3"
          },
          "title": "Podigee CORS Test"
        }
      }`

Screenshot:
![datei 25 11 16 09 37 01](https://cloud.githubusercontent.com/assets/1970014/20619067/c2267d16-b2f2-11e6-869d-6c2a35432778.png)

**Comment by benzimmer** [comment]
This should be fixed in the current version.
