### ISSUE TITLE
Rendering Bugs on iOS Safari

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#3]
Rendering Bugs on iOS Safari. This only happens in Safari on small screens. Do you know why?

![img_2698](https://cloud.githubusercontent.com/assets/144173/11985024/0ac0600a-a9c1-11e5-997d-b4d6b3a4fc00.PNG)
![img_2695](https://cloud.githubusercontent.com/assets/144173/11985031/13cb9372-a9c1-11e5-9d21-12e32aff3f13.PNG)

PS: If you want you can checkout podperlen.de to test. However please do not spread the word yet. It is still not public and in development.

**Comment by benzimmer** [comment]
This should be fixed with 8baceceb8b29fd077fab7eef9664ce148c6f6018

Unfortunately I was not able to test on your URL. I only see this:
<img width="355" alt="screen shot 2015-12-24 at 00 10 06" src="https://cloud.githubusercontent.com/assets/164417/11986686/bef72246-a9d2-11e5-9a2f-691b776c69eb.png">

**Comment by funkenstrahlen** [comment]
You are amazing! 😃
