### ISSUE TITLE
Player does not initialize in Chrome when using browsers back/forward buttons

### ISSUE THREAD

**Issue by dirkholzapfel** [podigee/podigee-podcast-player#30]
Use Google Chrome, go to https://www.podigee.com/en/podcast-player/ (-> the player loads), use the back button of the browser, use the forward button of the browser (the player does not load)

Google Chrome, Version 60.0.3112.113 (Official Build) (64-bit), macOS Sierra

http://podigee.github.io/podigee-podcast-player/ works correctly, it seems to have an older build version.

**Comment by benzimmer** [comment]
This was fixed with fbae35944c85e71cf52d6572c34e83c0f471570d
