### ISSUE TITLE
Playlist - times show up as NaN

### ISSUE THREAD

**Issue by efficienthacks** [podigee/podigee-podcast-player#33]
I can see that my player durations are all correct in my podcast feed xml (they are in seconds in the <duration> field.

Other podcast players parse the duration fine, but it shows up as NaN - I ended up just commenting out the duration, but it would be nice to have a real fix.

**Comment by benzimmer** [comment]
Can you please let me know how you use the player? From our CDN or do you build it yourself? If the second, did you try the latest version from this repository?

If you used the latest version, it would be awesome if you could share your feed URL so I can have a closer look at the issue.

**Comment by benzimmer** [comment]
Closing bc of missing info
