### ISSUE TITLE
locale error

### ISSUE THREAD

**Issue by tcbtcb** [podigee/podigee-podcast-player#37]
Hello - I have been using this player on my own web site for a while. At some point in the last four weeks or so, the player quit working. When I look in Chrome devtools I see this error

```
Uncaught TypeError: Cannot read property 'locale' of undefined
    at t.setConfigurations (podigee-podcast-player.html?id=d3862fc&iframeMode=script:242)
```

The animation starts but the player/file doesn't load. The mp3 and config json are hosted on a google storage bucket, CORS is enable and working, so no errors there. The player was working great for all of 2017. If there is a config issue I'd be interested in a bit of help.

**Comment by dirkholzapfel** [comment]
It's a bug with the locale fallback. As a workaround you can add 
```
options: {
  locale: "en"
}
```
to the player config.

**Comment by dirkholzapfel** [comment]
I think it was introduced by https://github.com/podigee/podigee-podcast-player/commit/4f6417f243233198b882919c22ddf3306d36fbee

**Comment by tcbtcb** [comment]
That config fixed it first run. Thanks a ton. Do you want me to document this anywhere and send a PR?

**Comment by benzimmer** [comment]
I'll fix this in the player today.

**Comment by benzimmer** [comment]
The fix is in and currently rolling out to the CDN (if you use that). Please let me know if that fixes your issues!

**Comment by tcbtcb** [comment]
It absolutely does. Thanks very much for the quick response and help.
