### ISSUE TITLE
Any chance of using versioning and make some releases

### ISSUE THREAD

**Issue by lsolesen** [podigee/podigee-podcast-player#39]
I am trying to debug why my Podigee player stopped working on my website http://historie.vih.dk/podcasts/2017-09-19-thomassen-erindringer/ (it used to work, but stopped for some reason), and I noticed that you have not made any releases / version, so basically I am just using the latest code. I would be very helpful if it was possible to reference a certain release in the code, so it is easier to debug where the problem is - whether it is my own code, how I use Podigee or Podigee itself.

**Comment by benzimmer** [comment]
Thanks for opening the issue. The problem should be fixed now. We made some changes recently to catch empty configurations which caused this problem on your site.

We did not take updating the changelog more seriously in the last month, but I have updated it and will try to keep up with it as much as possible to prevent situations like this.

We constantly make changes to the player and push them to our CDN shortly after that. The widespread use of the player makes it hard to be on top of all issues that may arise. If you want to make completely sure of the version you are currently using please consider hosting the player yourself (I can provide some instructions if needed). We'll also discuss some form of versioning for the future, until then I can only direct you to the (from now on up to date) changelog unfortunately.

**Comment by lsolesen** [comment]
But what about just tagging a release for right now. If I should host the
player myself, I would also need to know which version I pulled down.
Thanks for working on this very useful player :)

Den 08/03/2018 18.11 skrev "Ben Zimmer" <notifications@github.com>:
