### ISSUE TITLE
Logo im Desktopbrowser riesig

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#4]
Ich setze den Podigee Player auf [podperlen.de](https://podperlen.de) ein.

Allerdings stört es mich ein wenig, dass das Logo im Desktopbrowser so groß angezeigt wird:

![screen shot 2016-02-15 at 21 33 23](https://cloud.githubusercontent.com/assets/144173/13059626/d346007c-d42b-11e5-96a2-dd06f56cce33.png)

Ist das so gedacht? Oder macht da mein CSS irgendwas kaputt?

**Comment by benzimmer** [comment]
So wie es aussieht greift das "Responsive-Verhalten" einfach zu früh. Werde ich korrigieren.

**Comment by benzimmer** [comment]
Sollte jetzt gefixt sein. Evtl. kann es durch das Caching noch etwas dauern bis es überall zu sehen ist.

**Comment by funkenstrahlen** [comment]
Wow super! Vielen lieben Dank :smiley:

**Comment by funkenstrahlen** [comment]
Ich mag den Podigee Player ja mittlerweile mehr als den Podlove Player. Nicht so überladen.
