### ISSUE TITLE
Multiple Episodes Not Supported?

### ISSUE THREAD

**Issue by aaronst** [podigee/podigee-podcast-player#44]
Does this player no longer support multiple episodes?

I remember you used to be able to specify a list of episodes in the config like:
```json
window.playerConfig = {
    "podcast": {
        "episodes": [
            ...
        ]
    }
}
```

But that doesn't seem to work anymore.

**Comment by benzimmer** [comment]
Hey @aaronst,

it's still supported. Can you give me more information on this? Is there an error message in the developer tools or something like this? Do you have a page you can give me where I can have a look myself?

**Comment by markusvoelter** [comment]
Trying to do that, too. Player does not start up.

**Comment by benzimmer** [comment]
@markusvoelter Same as before: If I don't have any information on how you or how the configuration looks like, I can't really help here.

**Comment by markusvoelter** [comment]
<p>
<script>
window.playerConfiguration = {
  "podcast": {
    "episodes": [
      {
      	"url": "http://omegataupodcast.net/287-ozeane/",
       	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
       	"media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
       	"title": "omega tau 287 &#8211; Ozeane"
  	  },
  	  {
	    "url": "http://omegataupodcast.net/287-ozeane/",
    	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
	    "media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
    	"title": "omega tau 287 &#8211; Ozeane",
      }
    ]
  }
}
</script>
<script class="podigee-podcast-player" 
        src="https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js" 
        data-configuration="playerConfiguration">
</script>
</p>

**Comment by markusvoelter** [comment]
<p>
<script>
window.playerConfiguration = {
  "podcast": {
    "episodes": [
      {
      	"url": "http://omegataupodcast.net/287-ozeane/",
       	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
       	"media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
       	"title": "omega tau 287 &#8211; Ozeane"
  	  },
  	  {
	    "url": "http://omegataupodcast.net/287-ozeane/",
    	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
	    "media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
    	"title": "omega tau 287 &#8211; Ozeane",
      }
    ]
  }
}
</script>
<script class="podigee-podcast-player" 
        src="https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js" 
        data-configuration="playerConfiguration">
</script>
</p>

**Comment by markusvoelter** [comment]
Here is the code. I had also tried with various other additional tags, like those given in the example config file. The non-working player is here: http://omegataupodcast.net/play/

**Comment by benzimmer** [comment]
@markusvoelter You also need to specify the episode to play by default like this:

```javascript
window.playerConfiguration = {
  "episode": {
    "url": "http://omegataupodcast.net/287-ozeane/",
    "coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
    "media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
    "title": "omega tau 287 &#8211; Ozeane"
  },
  "podcast": {
    "episodes": [
      {
      	"url": "http://omegataupodcast.net/287-ozeane/",
       	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
       	"media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
       	"title": "omega tau 287 &#8211; Ozeane"
  	  },
  	  {
	    "url": "http://omegataupodcast.net/287-ozeane/",
    	"coverUrl": "http://omegataupodcast.net/rssimages/omegatau_2048x2048.png",
	    "media": {"mp3": "http://traffic.libsyn.com/omegataupodcast/omegatau-287-ozeane.mp3"},
    	"title": "omega tau 287 &#8211; Ozeane",
      }
    ]
  }
}
```

**Comment by markusvoelter** [comment]
Alright, works. Thank you VERY MUCH for your quick reply.

**Comment by benzimmer** [comment]
You're welcome!
