### ISSUE TITLE
Build output shows only the Animation, Nothing else.

### ISSUE THREAD

**Issue by muthughilli** [podigee/podigee-podcast-player#45]
Hi, 
I just installed npm, yarn, gulp in my machine. build has been done on the open source package using 'gulp build'. When i launch the output package nothing happens in the page, but only the loading animation appears. Please find the attached screenshot. Also I don't find any errors in the console. Not sure what basic procedure I miss here. Please guide me on this. Also, It would be great if you could provide a sample output package so that i can refer the output.
![gulpoutput](https://user-images.githubusercontent.com/12163366/39301795-13a4333c-496e-11e8-8e23-acbcddf931c4.PNG)
[gulp_output (1).zip](https://github.com/podigee/podigee-podcast-player/files/1950792/gulp_output.1.zip)

**Comment by benzimmer** [comment]
What you are trying to do is not possible. Please have a look at the readme and `index.html` on how to use the player code. Basically you need to provide a configuration and then add a script tag with the built JS code as the src.

If you run `gulp serve` and open https://localhost:8081 you will see the `index.html` rendered.
