### ISSUE TITLE
Custom theme problem violates "same origin policyN"

### ISSUE THREAD

**Issue by michaeljakob** [podigee/podigee-podcast-player#51]
I use podigee on https://www.alleaktien.de/walt-disney-aktienanalyse-auf-dem-weg-zur-zweiten-netflix/ with a custom CSS and custom HTML file.

I have one more issue now, I'm getting a violation of the "same origin policy":

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cdn.podigee.com' is therefore not allowed access.

Do you have an idea how we could go about this?

Regards,
Michael

**Comment by benzimmer** [comment]
You need to either host the player on the same domain as the themes or provide CORS headers (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) on the endpoint that serves the theme files.

**Comment by michaeljakob** [comment]
Hey Ben,
I tried both methods, none worked.


1) How do I properly set it up locally? Just copying the .js and the .html did NOT work? Do you have a clear and simple-to-understand documentation on how to set it up locally? (why is it so complicated?)

2) I tried CORS and added the following to lines to our .htaccess:
```
Access-Control-Allow-Origin: https://podigee.com
Access-Control-Allow-Origin: https://cdn.podigee.com

```
This crashed the website with an "error 500" -- am I not using it correctly?

**Comment by michaeljakob** [comment]
Hey ben,
is there any other way to fix the cross-origin issue?

**Comment by benzimmer** [comment]
We do not provide a guide for self hosting currently.

To host the player code yourself, please follow the instructions [here](https://github.com/podigee/podigee-podcast-player#contribute) and execute `gulp build` after installing the dependencies. After that you will find all necessary files in the `build/` folder.

**Comment by benzimmer** [comment]
@michaeljakob You do not have to use gulp on the server, you can build the assets locally and transfer them via FTP (or similar).

About CORS: It works exactly the other way around. Your website needs to allow the code hosted on cdn.podigee.com to fetch the theme files from alleaktien.de. You can find a lot of information how to do it with different servers here: https://enable-cors.org/index.html
