### ISSUE TITLE
Control player from outside the iframe

### ISSUE THREAD

**Issue by terhuerne** [podigee/podigee-podcast-player#57]
Hi there,

I want to trigger events inside the player after it has been loaded. For example trigger it to play. Is there an API to interact with the player through the embed code?

Thanks,
Johannes

**Comment by benzimmer** [comment]
Yes, we implemented the player.js API for that: http://playerjs.io/

Please see here for the list of implemented events/methods: https://github.com/podigee/podigee-podcast-player/blob/master/src/javascripts/extensions/playerjs/adapter.coffee
