### ISSUE TITLE
Possibility to copy embed code

### ISSUE THREAD

**Issue by benzimmer** [podigee/podigee-podcast-player#6]
A listener should be able to copy the embed code from the sharing extension.

**Comment by funkenstrahlen** [comment]
This is a very nice and important feature!

**Comment by benzimmer** [comment]
This is working [now](7cbf4ef88853d7519547df2f73dca8e6d7786d8d). By default it uses the code that was used for the current player. This can be overridden by passing `episode.embedCode` into the configuration.

**Comment by funkenstrahlen** [comment]
How does this work? Do I have to enable the extension? Or is it only active if I define the `episode.embedCode`?

**Comment by benzimmer** [comment]
Ah, I see. Currently you also need to add `episode.url` to enable the share extension. I'll fix that in the next days.

**Comment by funkenstrahlen** [comment]
I think this restriction is good! Keep it.

Some more docu in the Readme should be enough.

**Comment by funkenstrahlen** [comment]
I currently do not have my episode-data as a separate json file as it is required for the share extension to work.

This might become a problem when you do that: `By default it uses the code that was used for the current player`.

I know I can change that, however using this by default might cause problems for users if they do not know about the update?

**Comment by benzimmer** [comment]
You're right. I think the sharing the embed code needs to be restricted to players that are configured via a JSON file. The embed won't work anyway without that.
