### ISSUE TITLE
Passing configuration as a JSON removes all the spaces

### ISSUE THREAD

**Issue by rodrigoaguilera** [podigee/podigee-podcast-player#60]
Related to the same effort on
https://github.com/podigee/podigee-podcast-player/issues/59

I also tried the undocumented way of passing configuration directly as a json object.
It works great except for the small detail that all the spaces are removed so the titles look ugly.
```HTML
<script class="podigee-podcast-player" src="https://cdn.podigee.com/podcast-player/javascripts/podigee-podcast-player.js" data-configuration='{"episode": {"media": {"mp3": "http://example.com/files/2019-01/viola2.mp3"},"title": "Transcript Test"}}'></script>
```
With this example I see "TranscriptTest" instead of "Transcript test"

What are you trying to achieve by removing all the spaces? should't trimming be enough?

Thanks for such a great library

**Comment by benzimmer** [comment]
Thanks for opening the issue. I just fixed the underlying problem and the spaces should not be removed anymore.
