### ISSUE TITLE
Need to know current time of playback

### ISSUE THREAD

**Issue by emergingdzns** [podigee/podigee-podcast-player#66]
I've got this player integrated in a test environment and it's fantastic. However, there's one element that we are missing. We need to be able every x seconds to poll the player to get the user's current position in the playback in seconds.

Is there a way to do this? If so are there any examples?

**Comment by benzimmer** [comment]
The player supports the [player.js](http://playerjs.io/) API. You can find some documentation on which events it supports here: https://help.podigee.com/article/317-podcast-player-api
