### ISSUE TITLE
Resize player iframe when screen gets resized

### ISSUE THREAD

**Issue by benzimmer** [podigee/podigee-podcast-player#7]
The player iframe should resize when the window resizes.

**Comment by benzimmer** [comment]
Done with c7918a11478aebe15b347749b03a9c4123cd0a26

**Comment by funkenstrahlen** [comment]
I just tested this on my site, however the width of the iframe only gets updated when I reload the page. If I set the iframe width to `100%` it seems to work fine except there should be a minimal width.

**Comment by benzimmer** [comment]
The horizontal size of the iframe needs to be set by the surrounding site. The player inside the iframe does not care about the window size but only about the size of the iframe. Best-practice would be to set the iframe width to 100% with a min-width if you like.

**Comment by funkenstrahlen** [comment]
Ok got it. Thanks.
