### ISSUE TITLE
Unable to play any mp3 that is not hosted at `cdn.podigee.com` with CDN

### ISSUE THREAD

**Issue by smacz42** [podigee/podigee-podcast-player#86]
I've been playing around with the same setup as #85, and found that there does not seem to be any support by the CDN for mp3's or other media files that are hosted outside of the `cdn.podigee.com` domain. Is that the case?

**Comment by smacz42** [comment]
Apparently this is the expected behavior.

**Comment by benzimmer** [comment]
This is not expected behaviour. Can you tell me what leads you to this conclusion?

**Comment by smacz42** [comment]
I went and proved myself wrong.

Turns out the issue was with an addon blocking access to the media files that were being linked to. Re-running this in a vanilla browser works as expected. Sorry for the noise.
