### ISSUE TITLE
Should not display separator line if there is only one download format

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-podcast-player#9]
![screen shot 2016-02-21 at 18 18 19](https://cloud.githubusercontent.com/assets/144173/13204115/b9779732-d8c7-11e5-98ff-e381b83a63bd.png)

If there is only one file format available for download the player should not display a separator line.

**Comment by funkenstrahlen** [comment]
Did you already fix this, because I can not reproduce it any more right now?

**Comment by benzimmer** [comment]
No, the code for this hasn't changed since 11/2015. My best guess is there was weird media entry in the configuration that caused this, but I was not able to reproduce this in any way

[Heisenbug :)](https://en.wikipedia.org/wiki/Heisenbug)?!
