### ISSUE TITLE
Can't get player to auto-play next episodes in a playlist

### ISSUE THREAD

**Issue by tunnelsup** [podigee/podigee-podcast-player#94]
I've made a sweet little playlist. Clicking any of the tracks works great. But when a track ends the player does not automatically go to the next track and keep playing. I've also noticed this is the same behavior on the demos that have playlists too. 

I'm not sure I understand the point of a playlist if it can't autoplay to the next episode when the current one ends...

**Comment by benzimmer** [comment]
Autoplay is generally not considered good practice in the podcast world, that is why the player does not support it.
